const data = {
  username: "",
  columns: {
    0: {
      id: 0,
      title: "To Do",
      cards: ["0", "1"],
    },
    1: {
      id: 1,
      title: "In Progress",
      cards: ["2", "3"],
    },
    2: {
      id: 2,
      title: "Done",
      cards: ["4", "5"],
    },
    3: {
      id: 3,
      title: "Doing",
      cards: ["6", "7"],
    },
  },
  cards: {
    0: {
      cardid: "0",
      id: 0,
      title: "TitleTODO",
      description: "",
      comment: ["0", "1", "2"],
    },
    1: {
      cardid: "1",
      id: 1,
      title: "Title2",
      description: "Detailed description",
      comment: ["3", "4", "5"],
    },
    2: {
      cardid: "2",
      id: 2,
      title: "Title inProgress",
      description: "",
      comment: ["6", "7", "8"],
    },
    3: {
      cardid: "3",
      id: 3,
      title: "Title2",
      description: "Detailed description",
      comment: ["9", "10", "11"],
    },
    4: {
      cardid: "4",
      id: 4,
      title: "TitleDone",
      description: "",
      comment: ["12", "13", "14"],
    },
    5: {
      cardid: "5",
      id: 5,
      title: "Title2",
      description: "Detailed description",
      comment: ["15", "16", "17"],
    },
    6: {
      cardid: "6",
      id: 6,
      title: "TitleDoing",
      description: "",
      comment: ["18", "19", "20"],
    },
    7: {
      cardid: "7",
      id: 7,
      title: "Title2",
      description: "Detailed description",
      comment: ["21", "22", "23"],
    },
  },
  comment: {
    0: {
      commentid: "0",
      id: 0,
      author: "Ivan",
      text: "hello",
    },
    1: {
      commentid: "1",
      id: 1,
      author: "Boris",
      text: "hi",
    },
    2: {
      commentid: "2",
      id: 2,
      author: "Evgeny",
      text: "I`m frontend developer",
    },
    3: {
      commentid: "3",
      id: 3,
      author: "Ivan",
      text: "hello",
    },
    4: {
      commentid: "4",
      id: 4,
      author: "Boris",
      text: "hi",
    },
    5: {
      commentid: "5",
      id: 5,
      author: "Evgeny",
      text: "I`m frontend developer",
    },
    6: {
      commentid: "6",
      id: 6,
      author: "Danil",
      text: "FR",
    },
    7: {
      commentid: "7",
      id: 7,
      author: "Anton",
      text: "BB",
    },
    8: {
      commentid: "8",
      id: 8,
      author: "Masha",
      text: "Java",
    },
    9: {
      commentid: "9",
      id: 9,
      author: "Ivan",
      text: "hello",
    },
    10: {
      commentid: "10",
      id: 10,
      author: "Boris",
      text: "hi",
    },
    11: {
      commentid: "11",
      id: 11,
      author: "Evgeny",
      text: "I`m frontend developer",
    },
    12: {
      commentid: "12",
      id: 12,
      author: "Kirill",
      text: "AWP",
    },
    13: {
      commentid: "13",
      id: 13,
      author: "Kolya",
      text: "M4A1",
    },
    14: {
      commentid: "14",
      id: 14,
      author: "Olya",
      text: "Test",
    },
    15: {
      commentid: "15",
      id: 15,
      author: "Ivan",
      text: "hello",
    },
    16: {
      commentid: "16",
      id: 16,
      author: "Boris",
      text: "hi",
    },
    17: {
      commentid: "17",
      id: 17,
      author: "Evgeny",
      text: "I`m frontend developer",
    },
    18: {
      commentid: "18",
      id: 18,
      author: "Kostya",
      text: "Sea",
    },
    19: {
      commentid: "19",
      id: 19,
      author: "Boris",
      text: "hi",
    },
    20: {
      commentid: "20",
      id: 20,
      author: "Evgeny",
      text: "I`m frontend developer",
    },
    21: {
      commentid: "21",
      id: 21,
      author: "Ivan",
      text: "hello",
    },
    22: {
      commentid: "22",
      id: 22,
      author: "Boris",
      text: "hi",
    },
    23: {
      commentid: "23",
      id: 23,
      author: "Evgeny",
      text: "I`m frontend developer",
    },
  },
};

export default data;
